# Cutlets


#### Ho=There is no significant difference in the diameter of the cutlet between two units
#### Ha=There is a significant difference in the diameter of the cutlet between two units

In [1]:
import statsmodels.api as sm
import scipy.stats as stats
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [9]:
df=pd.read_csv('Cutlets.csv')

In [10]:
df.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [31]:
unitA=df.iloc[:,0]
unitA.mean()

7.01909142857143

In [32]:
unitB=df.iloc[:,1]
unitB.mean()

6.964297142857142

In [46]:
p=stats.ttest_ind(unitA,unitB)
p

Ttest_indResult(statistic=0.7228688704678061, pvalue=0.4722394724599501)

In [57]:
if p[1]<0.05:
    print('Reject null hypothesis:There is a significant difference in the diameter of the cutlet between two units')
else:
    print('Do not reject null hypothesis: There is no significant difference in the diameter of the cutlet between two units')

Do not reject null hypothesis: There is no significant difference in the diameter of the cutlet between two units


# LabTAT

#### Ho=There is no difference in average TAT among the different laboratories
#### Ha=There is a difference in average TAT among the different laboratories

In [47]:
df2=pd.read_csv('LabTAT.csv')

In [107]:
df2

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0          185.35        165.53        176.70        166.13
1          170.49        185.91        198.45        160.79
2          192.77        194.92        201.23        185.18
3          177.33        183.00        199.61        176.42
4          193.41        169.57        204.63        152.60
..            ...           ...           ...           ...
115        178.49        170.66        193.80        172.68
116        176.08        183.98        215.25        177.64
117        202.48        174.54        203.99        170.27
118        182.40        197.18        194.52        150.87
119        182.09        215.17        221.49        162.21

[120 rows x 4 columns]

In [67]:
df2.mean()

Laboratory 1    178.361583
Laboratory 2    178.902917
Laboratory 3    199.913250
Laboratory 4    163.682750
dtype: float64

In [76]:
p1=stats.f_oneway(df2.iloc[:,0],df2.iloc[:,1],df2.iloc[:,2],df2.iloc[:,3])
p1

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [77]:
if p1[1]<0.05:
    print('Reject null hypothesis:There is a significant difference in average TAT among the different laboratories')
else:
    print('Do not reject null hypothesis: There is no significant difference in average TAT among the different laboratories')

Reject null hypothesis:There is a significant difference in average TAT among the different laboratories


# Buyer Ratio

#### Ho: male-female buyer rations are different across regions i.e no dependence
#### Ha: male-female buyer rations are similar across regions ie. dependence

In [99]:
from scipy.stats import chi2_contingency,chi2
import pandas as pd
import numpy as np

In [80]:
df3=pd.read_csv('BuyerRatio.csv')

In [86]:
df3

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [90]:
observed=df3.iloc[:,1:].values

In [91]:
observed

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]], dtype=int64)

In [95]:
stat, p, dof, expected = chi2_contingency(observed)

In [97]:
print('dof=%d' % dof)
print(expected)

dof=3
[[  42.76531299  146.81287862  131.11756787   72.30424052]
 [ 442.23468701 1518.18712138 1355.88243213  747.69575948]]


In [101]:
prob = 0.95
critical = chi2.ppf(prob, dof)
print('probability=%.3f, critical=%.3f, stat=%.3f' % (prob, critical, stat))
if abs(stat) >= critical:
	print('Dependent (reject H0)')
else:
	print('Independent (fail to reject H0)')
    
# interpret p-value
alpha = 1.0 - prob
print('significance=%.3f, p=%.3f' % (alpha, p))
if p <= alpha:
	print('Dependent (reject H0)')
else:
	print('Independent (fail to reject H0)')

probability=0.950, critical=7.815, stat=1.596
Independent (fail to reject H0)
significance=0.050, p=0.660
Independent (fail to reject H0)


# CustomerOrderForm

#### Ho: Defective % doesnt varies between various centers
#### Ha: Defective % varies in atleast one centers

In [116]:
import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency,chi2
from sklearn.preprocessing import LabelEncoder

In [118]:
df4=pd.read_csv('CustomerOrderForm.csv')

In [119]:
df4.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [124]:
label_encoder= LabelEncoder()
df4['Phillippines']=label_encoder.fit_transform(df4['Phillippines'])
df4['Indonesia']=label_encoder.fit_transform(df4['Indonesia'])
df4['Malta']=label_encoder.fit_transform(df4['Malta'])
df4['India']=label_encoder.fit_transform(df4['India'])

In [130]:
df4.to_csv('EDA_CustomerOrderForm.csv')

In [132]:
df4

Phillippines  Indonesia  Malta  India
0               1          1      0      1
1               1          1      1      0
2               1          0      0      1
3               1          1      1      1
4               1          1      0      1
..            ...        ...    ...    ...
295             1          1      1      1
296             1          1      1      1
297             1          1      0      1
298             1          1      1      1
299             1          0      0      1

[300 rows x 4 columns]

In [133]:
p2=stats.f_oneway(df4.iloc[:,0],df4.iloc[:,1],df4.iloc[:,2],df4.iloc[:,3])

In [135]:
p2

F_onewayResult(statistic=1.286168556089167, pvalue=0.2776780955705948)

In [136]:
if p2[1]<0.05:
    print('Reject null hypothesis:Defective % doesnt varies between various centers')
else:
    print('Do not reject null hypothesis: Defective % varies in atleast one centers')

Do not reject null hypothesis: Defective % varies in atleast one centers


### CustomerOrderForm (Chi2 Test)

In [1]:
import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency,chi2

In [2]:
df5=pd.read_csv('CustomerOrderForm.csv')

In [3]:
df5.head(5)

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [9]:
a=sum(df5['Phillippines']=='Error Free')
b=sum(df5['Phillippines']=='Defective')

c=sum(df5['Indonesia']=='Error Free')
d=sum(df5['Indonesia']=='Defective')

e=sum(df5['Malta']=='Error Free')
f=sum(df5['Malta']=='Defective')

g=sum(df5['India']=='Error Free')
h=sum(df5['India']=='Defective')

In [10]:
a,b,c,d,e,f,g,h

(271, 29, 267, 33, 269, 31, 280, 20)

In [18]:
Error_Free=[a,c,e,g]
Defective=[b,d,f,h]

In [33]:
df6=pd.DataFrame([Error_Free,Defective],columns=['Phillippines','Indonesia','Malta','India'])
df6

Phillippines  Indonesia  Malta  India
0           271        267    269    280
1            29         33     31     20

In [35]:
df7=pd.DataFrame({'Observed Values':['Error_Free','Defective']})
df7

Observed Values
0      Error_Free
1       Defective

In [46]:
df8=df7.join(df6)
df8

Observed Values  Phillippines  Indonesia  Malta  India
0      Error_Free           271        267    269    280
1       Defective            29         33     31     20

#### Ho: Error Free and Defective are different across regions i.e no dependence
#### Ha:Error Free and Defective are similar across regions ie. dependence 

In [51]:
observed=df8.iloc[:,1:].values

In [52]:
observed

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]], dtype=int64)

In [53]:
stat, p, dof, expected = chi2_contingency(observed)

In [54]:
print('dof=%d' % dof)
print(expected)

dof=3
[[271.75 271.75 271.75 271.75]
 [ 28.25  28.25  28.25  28.25]]


In [55]:
prob = 0.95
critical = chi2.ppf(prob, dof)
print('probability=%.3f, critical=%.3f, stat=%.3f' % (prob, critical, stat))
if abs(stat) >= critical:
	print('Dependent (reject H0)')
else:
	print('Independent (fail to reject H0)')
    
# interpret p-value
alpha = 1.0 - prob
print('significance=%.3f, p=%.3f' % (alpha, p))
if p <= alpha:
	print('Dependent (reject H0)')
else:
	print('Independent (fail to reject H0)')

probability=0.950, critical=7.815, stat=3.859
Independent (fail to reject H0)
significance=0.050, p=0.277
Independent (fail to reject H0)
